# Generated by Django 4.0.5 on 2022-06-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_note_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('complete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'RecipeProject',
                'verbose_name_plural': 'RecipeProjects',
            },
        ),
        migrations.RemoveField(
            model_name='recipeversion',
            name='version_number',
        ),
        migrations.AddField(
            model_name='note',
            name='note_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
