# Generated by Django 4.0.5 on 2022-06-29 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_note_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.RenameField(
            model_name='tasterfeedback',
            old_name='tester',
            new_name='taster',
        ),
    ]
