# Generated by Django 4.0.5 on 2022-06-27 17:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_recipeproject_remove_recipeversion_version_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeproject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeversion',
            name='project',
            field=models.ForeignKey(max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_versions', to='api.recipeproject'),
        ),
        migrations.AddField(
            model_name='recipeversion',
            name='version_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipeproject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
