# Generated by Django 4.0.5 on 2022-06-28 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_recipeproject_created_at_recipeversion_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeversion',
            name='project',
        ),
        migrations.AddField(
            model_name='recipeproject',
            name='recipe',
            field=models.ForeignKey(max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_projects', to='api.recipeversion'),
        ),
    ]
