# Generated by Django 4.0.5 on 2022-06-28 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('api', '0025_recipe_delete_ingredient_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeVersion',
            new_name='RecipeVariation',
        ),
        migrations.AlterModelOptions(
            name='recipevariation',
            options={'verbose_name': 'RecipeVariaton', 'verbose_name_plural': 'RecipeVariations'},
        ),
    ]
