# Generated by Django 4.0.5 on 2022-06-28 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_rename_recipeversion_recipevariation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasterfeedback',
            old_name='tester',
            new_name='taster',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='api.recipevariation'),
        ),
    ]
