# Generated by Django 4.0.5 on 2022-06-29 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_rename_tester_tasterfeedback_taster_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipevariation',
            name='variation_number',
            field=models.ForeignKey(max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_variations', to='api.recipevariation'),
        ),
        migrations.AlterField(
            model_name='recipevariation',
            name='chef',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_variations', to=settings.AUTH_USER_MODEL),
        ),
    ]
